# Generated by Django 5.1.4 on 2025-02-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batdongsan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('year', models.IntegerField(default=2024)),
                ('startDate', models.DateField()),
                ('active', models.BooleanField()),
                ('local_TT' , models.CharField(max_length= 50,blank = True )),
                ('information', models.TextField("",blank=True)),
                ('price', models.CharField(max_length= 20,blank=True)),
                ('area' , models.CharField(max_length=99,blank=True)),
                ('profile_picture' , models.ImageField(upload_to='photos/'))
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('local', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=13)),
                ('profile_picture' , models.ImageField(upload_to='photos/'))
            ],
        ),
    ]
