# Generated by Django 5.1.4 on 2025-02-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batdongsan',
            name='category',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
