# Generated by Django 5.1.4 on 2025-02-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0005_rename_customer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(),
        ),
    ]
