# Generated by Django 5.1.4 on 2025-02-10 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0006_alter_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fullName',
        ),
    ]
