# Generated by Django 5.1.4 on 2025-02-11 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0007_remove_profile_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
