# Generated by Django 5.1.4 on 2025-02-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0010_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
