# Generated by Django 5.1.4 on 2025-02-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0011_blog_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='dayUpBlog',
            field=models.DateField(blank=True, null=True),
        ),
    ]
