# Generated by Django 5.1.4 on 2024-12-27 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinhThanh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_tinh_thanh', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DuAn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_du_an', models.CharField(max_length=100)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('tinh_thanh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tinhthanh')),
            ],
        ),
        migrations.CreateModel(
            name='BatDongSan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai', models.CharField(choices=[('Nhà ở', 'Nhà ở'), ('Đất', 'Đất')], max_length=50)),
                ('dia_chi', models.CharField(max_length=255)),
                ('gia', models.DecimalField(decimal_places=2, max_digits=15)),
                ('du_an', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.duan')),
                ('tinh_thanh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tinhthanh')),
            ],
        ),
    ]
