# Generated by Django 5.1.4 on 2024-12-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tinhthanh_duan_batdongsan'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTDuAn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=100)),
                ('gia_ban', models.BigIntegerField(verbose_name=99999999999)),
                ('dia_chi', models.CharField(max_length=255)),
                ('mo_ta', models.TextField()),
                ('ngay_ban', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=25)),
                ('gioi_tinh', models.BooleanField()),
                ('so_dien_thoai', models.CharField(max_length=11)),
            ],
        ),
        migrations.RemoveField(
            model_name='duan',
            name='tinh_thanh',
        ),
        migrations.RemoveField(
            model_name='batdongsan',
            name='du_an',
        ),
        migrations.DeleteModel(
            name='Example',
        ),
        migrations.RemoveField(
            model_name='batdongsan',
            name='dia_chi',
        ),
        migrations.RemoveField(
            model_name='batdongsan',
            name='gia',
        ),
        migrations.RemoveField(
            model_name='batdongsan',
            name='loai',
        ),
        migrations.RemoveField(
            model_name='batdongsan',
            name='tinh_thanh',
        ),
        migrations.DeleteModel(
            name='DuAn',
        ),
    ]
